-- MySQL Script generated by MySQL Workbench
-- Thứ tư, 07 Tháng ba Năm 2018 10:26:10 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assignment01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment01` DEFAULT CHARACTER SET latin1 ;
USE `assignment01` ;

-- -----------------------------------------------------
-- Table `assignment01`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment01`.`customer` (
  `customerId` INT(11) NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(255) NULL DEFAULT NULL,
  `customerAddress` VARCHAR(255) NULL DEFAULT NULL,
  `customerAge` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`customerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `assignment01`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment01`.`product` (
  `productNumber` INT(11) NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(255) NULL DEFAULT NULL,
  `dateOfPayment` DATE NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `customer_customerId` INT(11) NOT NULL,
  PRIMARY KEY (`productNumber`),
  INDEX `fk_product_customer_idx` (`customer_customerId` ASC),
  CONSTRAINT `fk_product_customer`
    FOREIGN KEY (`customer_customerId`)
    REFERENCES `assignment01`.`customer` (`customerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
