package com.example.demo.entity;
// Generated Mar 7, 2018 10:29:30 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "assignment01")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String customerName;
	private String customerAddress;
	private Integer customerAge;

	public Customer() {
	}

	public Customer(String customerName, String customerAddress, Integer customerAge) {
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerAge = customerAge;
	}
	public Customer(Integer customerId,String customerName, String customerAddress, Integer customerAge) {
		this.customerId=customerId;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.customerAge = customerAge;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customerId", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customerName")
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customerAddress")
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "customerAge")
	public Integer getCustomerAge() {
		return this.customerAge;
	}

	public void setCustomerAge(Integer customerAge) {
		this.customerAge = customerAge;
	}

}
