package com.example.demo.entity;
// Generated Mar 7, 2018 10:29:30 AM by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "assignment01")
public class Product implements java.io.Serializable {

	private Integer productNumber;
	private String productName;
	private Date dateOfPayment;
	private Float price;
	
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); //yyyy/MM/dd

	public Product() {
	}

	public Product(String productName, Date date, Float price) throws ParseException {
		this.productName = productName;
		this.dateOfPayment = date;
		this.price = price;
	}
	
	public Product(Integer productNumber, String productName, Date date, Float price) throws ParseException {
		this.productNumber=productNumber;
		this.productName = productName;
		this.dateOfPayment = date;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "productNumber", unique = true, nullable = false)
	public Integer getProductNumber() {
		return this.productNumber;
	}

	public void setProductNumber(Integer productNumber) {
		this.productNumber = productNumber;
	}

	@Column(name = "productName")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateOfPayment", length = 10)
	public Date getDateOfPayment() {
		return this.dateOfPayment;
	}

	public void setDateOfPayment(Date dateOfPayment) {
		this.dateOfPayment = dateOfPayment;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

}
